product updates for art 3.12

diff --git a/releaseDB/lar_product_stack-cfg.in b/releaseDB/lar_product_stack-cfg.in
--- a/releaseDB/lar_product_stack-cfg.in
+++ b/releaseDB/lar_product_stack-cfg.in
@@ -14,22 +14,22 @@ EOF
   return ${status}
 fi
 
-pyver=v3_9_2
-pyqual=p392
+pyver=v3_9_13
+pyqual=p3913
 
-build_bundle hep_hpc_toolkit-@HEP_HPC_TOOLKIT_DOT_VERSION@ ${basequal} 
-status=$?
-if (( ${status} != 0)); then
-  cat 1>&2 <<EOF
-Build of hep_hpc_toolkit-@HEP_HPC_TOOLKIT_DOT_VERSION@ bundle failed with status ${status}
-EOF
-  return ${status}
-fi
+#build_bundle hep_hpc_toolkit-@HEP_HPC_TOOLKIT_DOT_VERSION@ ${basequal} 
+#status=$?
+#$if (( ${status} != 0)); then
+#  cat 1>&2 <<EOF
+#Build of hep_hpc_toolkit-@HEP_HPC_TOOLKIT_DOT_VERSION@ bundle failed with status ${status}
+#EOF
+#  return ${status}
+#fi
 
 do_build marley @MARLEY_VERSION@ ${basequal}
 do_build pandora @PANDORA_VERSION@ ${basequal}
 do_build rstartree @RSTARTREE_VERSION@
-#do_build hdf5 @HDF5_VERSION@ ${basequal}
+do_build hdf5 @HDF5_VERSION@ ${basequal}
 #do_build hep_hpc @HEP_HPC_VERSION@ ${basequal}
 do_build glpk @GLPK_VERSION@
 build_noarch eigen @EIGEN_VERSION@
@@ -38,7 +38,8 @@ build_noarch h5cpp @H5CPP_VERSION@
 do_build jsoncpp @JSONCPP_VERSION@ ${basequal}
 do_build golang @GOLANG_VERSION@
 do_build gojsonnet @GOJSONNET_VERSION@ ${basequal}
-do_build opencv @OPENCV_VERSION@ ${basequal}:${pyqual}
+# opencv no longer builds for c7
+[ "$basequal" = c7 ] || do_build opencv @OPENCV_VERSION@ ${basequal}:${pyqual}
 do_build sundials @SUNDIALS_VERSION@ ${basequal}
 do_build stan_math @STAN_MATH_VERSION@ ${basequal}
 do_build stan @STAN_VERSION@ ${basequal}
@@ -59,7 +60,5 @@ do_build pycurl @PYCURL_VERSION@ ${pyqual}
 
 # add to manifest if no build 
 build_noarch ifdhc_config @IFDHC_CONFIG_VERSION@
-#build_noarch genie_phyopt @GENIE_PHYOPT_VERSION@ dkstandard-resfixfix
-#build_noarch genie_phyopt @GENIE_PHYOPT_VERSION@ dkcharmtau-resfixfix
 
 return 0
